
DROP database IF EXISTS pos; CREATE database pos;
\upos
CREATE TABLE Zip
(
zip INT PRIMARY KEY,
city TEXT,
state TEXT
) ENGINE=InnoDB;

CREATE TABLE Customer
(
id int PRIMARY KEY,
firstName TEXT,
lastName TEXT,
email TEXT,
address TEXT,
birthDate DATE,
zip INT,
FOREIGN KEY(zip) REFERENCES Zip(zip)
	ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE `Order`
(
id int PRIMARY KEY,
customerID INT,
FOREIGN KEY(customerID) REFERENCES Customer(id)
	ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE Product
(
id int PRIMARY KEY,
app TEXT,
price DECIMAL(4,2)
) ENGINE=InnoDB;

CREATE TABLE OrderLine
(
orderID INT,
productID INT,
quantity INT,
PRIMARY KEY(orderID, productID),
FOREIGN KEY(orderID) REFERENCES `Order`(id)
	ON DELETE RESTRICT ON UPDATE RESTRICT,
FOREIGN KEY(productID) REFERENCES Product(id)
	ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

LOAD DATA LOCAL INFILE '/home/ec2-user/Zip.csv'
INTO TABLE pos.Zip
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/ec2-user/Customer.csv'
INTO TABLE pos.Customer
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/ec2-user/Order.csv'
INTO TABLE pos.`Order`
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/ec2-user/Product.csv'
INTO TABLE pos.Product
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/ec2-user/OrderLine.csv'
INTO TABLE pos.OrderLine
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
